version: '3.7'

services:
  httpd:
    image: luzat/httpd:2.4
    env_file:
      - .env
    volumes:
      - ./htdocs:/var/www/htdocs
      - ./httpd/conf.d:/usr/local/apache2/conf/conf.d
      #- ./httpd/server.crt:/usr/local/apache2/conf/server.crt
      #- ./httpd/server.key:/usr/local/apache2/conf/server.key
    ports:
      - '80:80'
      - '443:443'
    working_dir: "/var/www/$HTTPD_DIR"

  php:
    build:
      context: php
      args:
      - DUID=$DUID
      - DGID=$DGID
    env_file:
      - .env
    environment:
      - HOME=/var/www/$HTTPD_DIR
    volumes:
      - ./htdocs:/var/www/htdocs
      - ./php/conf.d:/usr/local/etc/php/conf.d.local
      - mysql_socket:/var/run/mysqld
    user: "$DUID:$DGID"
    working_dir: "/var/www/$HTTPD_DIR"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=dev
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql_socket:/var/run/mysqld
    ports:
      - '3306:3306'
    user: "$DUID:$DGID"
    networks:
      default:
        aliases:
          - "$MYSQL_HOST"

  # Bridge localhost:3306 from PHP to MySQL
  mysql_bridge:
    image: alpine/socat
    command: TCP-LISTEN:3306,fork TCP:mysql:3306
    network_mode: service:php

# Optional services
#  adminer:
#    image: adminer
#    environment:
#    - ADMINER_DEFAULT_SERVER=mysql
#    ports:
#    - '8080:8080'

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_HOST=mysql
#      - PMA_PORT=3306
#      - PMA_USER=root
#      - PMA_PASSWORD=dev
#    ports:
#      - '8081:80'

#  redis:
#    image: redis
#    command: ['redis-server', '--appendonly', 'yes']
#    volumes:
#      - ./redis/data:/data

# Bridge UNIX socket from PHP to MySQL to support /var/run/mysqld/mysqld.sock
volumes:
  mysql_socket:


